### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by staFF6773** [geode-sdk/website#13]
Al iniciar la web en local me sale este error y ya instale todas las dependencias

```
████████████████████████████████████████ 99% Downloading mods indexnode:fs:1030
  binding.rename(
          ^

Error: EPERM: operation not permitted, rename 'C:\Users\Luis\Desktop\website\__mods\mods-main\mods-v2' -> 'C:\Users\Luis\Desktop\website\_mods_tmp'
    at renameSync (node:fs:1030:11)
    at file:///C:/Users/Luis/Desktop/website/build-mods-pages.js:38:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\Luis\\Desktop\\website\\__mods\\mods-main\\mods-v2',
  dest: 'C:\\Users\\Luis\\Desktop\\website\\_mods_tmp'
}

Node.js v21.5.0
node:internal/errors:956
  const err = new Error(message);
              ^

Error: Command failed: node build-mods-pages.js
    at genericNodeError (node:internal/errors:956:15)
    at wrappedFn (node:internal/errors:510:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///C:/Users/Luis/Desktop/website/build.js:20:5
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)        
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12) {  
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10716,
  stdout: null,
  stderr: null
}
```

**Comment by matcool** [comment]
why did you make the issue in spanish

**Comment by staFF6773** [comment]
> Member

When I start the web in local I get this error and I have already installed all the dependencies.
